#server:
#  port: 8082
#spring:
#  application:
#    name: tickets
#  profiles:
#    active: dev
#
#  jwt:
#    secret: ticket170720003jshada
#    expiration: 86400000
#
#  datasource:
#    url: jdbc:postgresql://localhost:5433/ticketdb
#    username: postgres
#    password: haki$1120
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-test-query: SELECT 1
#      validation-timeout: 5000
#      max-lifetime: 600000
#      connection-timeout: 2000
#      initialization-fail-timeout: -1
#
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: health,info
#  endpoint:
#    health:
#      show-details: always
#      show-components: always
#
#logging:
#  level:
#    root: INFO
#    org.springframework: WARN