spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ticketdb
    username: postgres
    password: haki$1120
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000         # 30s
      max-lifetime: 1740000       # 29m
      connection-timeout: 20000   # 20s
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: true
  main:
    banner-mode: off
  jackson:
    serialization:
      write_dates_as_timestamps: false
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: always
      show-components: always
server:
  port: 8081
jwt:
  secret: 4jsadhajkhd734y98qwdkln172ye8eu102askdjkash7
  expiration: 3600000
  refresh-expiration: 604800000
logging:
  level:
    com.kimhok.tickets: ERROR
    org.springframework.security: ERROR
    io.jsonwebtoken: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
bakong:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7ImlkIjoiMzFlYTI0NGUwYmUzNGYwMyJ9LCJpYXQiOjE3NjE0MDgwMDgsImV4cCI6MTc2OTE4NDAwOH0.NdBkPHick1Y4ehZYhqcaEJMFIJrmSwBm-iiWamBFsbs
  base-uri: https://api-bakong.nbc.gov.kh/v1